# Generated by Django 5.2.7 on 2025-10-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BCSCheckupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(verbose_name='답변 목록')),
                ('result_score', models.IntegerField(verbose_name='진단 결과 점수')),
                ('result_text', models.CharField(max_length=100, verbose_name='진단 결과 텍스트')),
                ('checkup_date', models.DateTimeField(auto_now_add=True, verbose_name='진단 일시')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='일정 날짜')),
                ('content', models.CharField(max_length=200, verbose_name='일정 내용')),
                ('category', models.CharField(choices=[('병원/약', '병원/약'), ('미용', '미용'), ('행사', '행사'), ('기타', '기타')], max_length=10, verbose_name='카테고리')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, verbose_name='할 일 내용')),
                ('is_complete', models.BooleanField(default=False, verbose_name='완료 여부')),
                ('log_date', models.DateField(verbose_name='해당 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('예방접종', '예방접종'), ('병원방문', '병원방문'), ('투약', '투약'), ('기타', '기타')], max_length=10, verbose_name='기록 종류')),
                ('content', models.TextField(verbose_name='내용')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='장소 또는 약 이름')),
                ('log_date', models.DateField(verbose_name='기록 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MealLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('사료', '사료'), ('간식', '간식'), ('특식', '특식'), ('영양제', '영양제')], max_length=10, verbose_name='종류')),
                ('food_name', models.CharField(max_length=100, verbose_name='사료/간식 이름')),
                ('quantity_gram', models.FloatField(verbose_name='양(g)')),
                ('calories_kcal', models.IntegerField(verbose_name='칼로리(kcal)')),
                ('log_date', models.DateField(verbose_name='기록 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('species', models.CharField(choices=[('강아지', '강아지'), ('고양이', '고양이')], max_length=10, verbose_name='종')),
                ('breed', models.CharField(max_length=100, verbose_name='품종')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('수컷', '수컷'), ('암컷', '암컷')], max_length=10, verbose_name='성별')),
                ('is_neutered', models.BooleanField(verbose_name='중성화 여부')),
                ('weight', models.FloatField(verbose_name='체중(kg)')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='프로필 사진')),
                ('target_activity_minutes', models.IntegerField(default=30, verbose_name='하루 목표 활동량(분)')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='건강 특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('산책', '산책'), ('실내놀이', '실내놀이'), ('훈련', '훈련'), ('기타', '기타')], max_length=10, verbose_name='활동 종류')),
                ('duration_minutes', models.IntegerField(verbose_name='활동 시간(분)')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='이동 거리(km)')),
                ('log_date', models.DateField(verbose_name='기록 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
