# Generated by Django 5.2.7 on 2025-10-31 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='주인'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_logs', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='healthlog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_logs', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='carelog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='calendarschedule',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='bcscheckupresult',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bcs_results', to='pets.pet'),
        ),
        migrations.AddField(
            model_name='walklog',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_logs', to='pets.pet'),
        ),
        migrations.AlterUniqueTogether(
            name='carelog',
            unique_together={('pet', 'log_date', 'content')},
        ),
    ]
