# Generated by Django 5.2.7 on 2025-11-02 18:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meallog',
            old_name='quantity_gram',
            new_name='quantity_g',
        ),
        migrations.RenameField(
            model_name='walklog',
            old_name='duration_minutes',
            new_name='duration',
        ),
        migrations.RemoveField(
            model_name='bcscheckupresult',
            name='result_score',
        ),
        migrations.RemoveField(
            model_name='bcscheckupresult',
            name='result_text',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='calories_kcal',
        ),
        migrations.RemoveField(
            model_name='meallog',
            name='meal_type',
        ),
        migrations.RemoveField(
            model_name='walklog',
            name='distance_km',
        ),
        migrations.AddField(
            model_name='bcscheckupresult',
            name='result_stage',
            field=models.CharField(default='', max_length=50, verbose_name='진단 결과 단계'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthlog',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='당시 체중 (kg)'),
        ),
        migrations.AddField(
            model_name='meallog',
            name='calorie',
            field=models.FloatField(default=0, verbose_name='칼로리(kcal)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meallog',
            name='food_type',
            field=models.CharField(choices=[('사료', '사료'), ('간식', '간식'), ('특식', '특식'), ('영양제', '영양제')], default='', max_length=50, verbose_name='종류 (사료, 간식 등)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='walklog',
            name='distance',
            field=models.FloatField(blank=True, null=True, verbose_name='이동 거리(km, 선택)'),
        ),
        migrations.AlterField(
            model_name='calendarschedule',
            name='category',
            field=models.CharField(choices=[('병원/약', '병원/약'), ('미용', '미용'), ('행사', '행사'), ('기타', '기타')], max_length=50, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='carelog',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='해당 날짜'),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='log_type',
            field=models.CharField(choices=[('예방접종', '예방접종'), ('병원방문', '병원방문'), ('투약', '투약'), ('기타', '기타')], max_length=50, verbose_name='기록 종류'),
        ),
        migrations.AlterField(
            model_name='meallog',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='기록 날짜'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_profiles/', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='target_activity_minutes',
            field=models.IntegerField(default=45, verbose_name='하루 목표 활동량(분)'),
        ),
        migrations.AlterField(
            model_name='walklog',
            name='log_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='기록 날짜'),
        ),
        migrations.AlterField(
            model_name='walklog',
            name='log_type',
            field=models.CharField(choices=[('산책', '산책'), ('실내놀이', '실내놀이'), ('훈련', '훈련'), ('기타', '기타')], default='산책', max_length=50, verbose_name='활동 종류'),
        ),
    ]
