# Generated by Django 5.2.7 on 2025-11-04 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255, verbose_name='알림 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='발생 시간')),
                ('notification_type', models.CharField(choices=[('message', '새 쪽지'), ('comment', '새 댓글'), ('like', '게시글 좋아요')], max_length=20, verbose_name='알림 종류')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='관련 링크')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='알림 수신자')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
